name: Tests
on: [pull_request]
jobs:
  unit_test_job:
    name: Unit
    runs-on: macOS-latest
    steps:
      # Checks out a copy of your repository
      - name: Checkout repository
        uses: actions/checkout@v1
      - name: Use Xcode 12.3
        run: sudo xcode-select -switch /Applications/Xcode_12.3.app
      - name: Install xcpretty
        run: gem install xcpretty
      - name: Install Carthage dependencies
        run: ./carthage.sh bootstrap
      - name: Run Unit Tests
        run: set -o pipefail && xcodebuild -workspace 'BraintreeDropIn.xcworkspace' -sdk 'iphonesimulator' -configuration 'Debug' -scheme 'UnitTests' -destination 'name=iPhone 11,platform=iOS Simulator'  test  | xcpretty
  ui_test_job:
    name: UI
    runs-on: macOS-latest
    steps:
      # Checks out a copy of your repository
      - name: Checkout repository
        uses: actions/checkout@v1
      - name: Use Xcode 12.3
        run: sudo xcode-select -switch /Applications/Xcode_12.3.app
      - name: Install xcpretty
        run: gem install xcpretty
      - name: Cache Carthage dependencies
        id: cache-carthage-deps
        uses: actions/cache@v2
        with:
          path: Carthage
          key: ${{ runner.os }}-carthage-${{ hashFiles('**/Cartfile.resolved') }}
          restore-keys: |
            ${{ runner.os }}-carthage-
      - name: Install Carthage Dependencies
        if: steps.cache-carthage-deps.outputs.cache-hit != 'true'
        run: ./carthage.sh bootstrap
      - name: Run UI Tests
        run: set -o pipefail && xcodebuild -workspace 'BraintreeDropIn.xcworkspace' -sdk 'iphonesimulator' -configuration 'Debug' -scheme 'UITests' -destination 'name=iPhone 11,platform=iOS Simulator'  test  | xcpretty
